=== HandeMapper/hand-e-mapper/handemapper.gui/src/main/resources/schema/gesturesXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:jxb="http://java.sun.com/xml/ns/jaxb"
            jxb:version="2.0">
   
  <!-- Simple type definitions -->
  
  <xsd:simpleType name="nameType">
    <xsd:restriction base="xsd:string">
      <xsd:minLength  value="1"/>
      <xsd:maxLength  value="48"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="descType">
    <xsd:restriction base="xsd:string">
      <xsd:minLength  value="1"/>
      <xsd:maxLength  value="96"/>
    </xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="isEnabledType">
    <xsd:restriction base="xsd:boolean"></xsd:restriction>
  </xsd:simpleType>
  
  <xsd:simpleType name="classType">
    <xsd:restriction base="xsd:anyURI"></xsd:restriction>
  </xsd:simpleType>
  
  <!-- Complex type definitions -->
  
  <xsd:complexType name="parameterType">
    <xsd:sequence>
      <xsd:element name="name" type="nameType" />
      <xsd:element name="description" type="descType" minOccurs="0"/>
      <xsd:element name="class" type="classType" />
      <xsd:element name="value" />
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="parametersType">
    <xsd:sequence>
      <xsd:element name="parameter" type="parameterType" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="gestureType">
    <xsd:sequence>
      <xsd:element name="name" type="nameType" />
      <xsd:element name="description" type="descType" minOccurs="0"/>
      <xsd:element name="isEnabled" type="isEnabledType" />
      <xsd:element name="class" type="classType" />
      <xsd:element name="parameters" type="parametersType" minOccurs="0" />
    </xsd:sequence>
  </xsd:complexType>
  
  <xsd:complexType name="gesturesType">
    <xsd:sequence>
      <xsd:element name="gesture" type="gestureType" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  
  <!-- The root type for the library -->
  
  <xsd:element name="gestures" type="gesturesType" />
  
</xsd:schema>

=== HandeMapper/hand-e-mapper/handemapper.gui/src/main/resources/gestures.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- last update on November 8, 2014 -->
<gestures xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="schema/gesturesXMLSchema.xsd">

  <gesture>
    <name>Hand Convexity/Contour Detection</name>
    <description>Hand detection using convexity and contour analysis.</description>
    <isEnabled>true</isEnabled>
    <class>handemapper.recognition.types.HandRecognizer</class>
  </gesture>
  
  <gesture>
    <name>Hand+Face Detection</name>
    <description>Hand detection using average skin tone from face detection.</description>
    <isEnabled>false</isEnabled>
    <class>handemapper.recognition.types.HaarClassifierGesture</class>
    <parameters>
      <parameter>
        <name>classifier</name>
        <description>Face classifier to help determine skin tone.</description>
        <class>java.io.File</class>
        <value>/classifiers/haarcascade_frontalface_default.xml</value>
      </parameter>
      <parameter>
        <name>highlightColor</name>
        <description>The highlight color of the face detection.</description>
        <class>java.awt.Color</class>
        <value>Color.RED</value>
      </parameter>
    </parameters>
  </gesture>
  
</gestures>
